"""Render firmware assets and trigger PlatformIO uploads."""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Iterable, List

from .config import (
    GENERATED_HEADER,
    OLED_HEIGHT,
    OLED_WIDTH,
    REPO_ROOT,
)
from .platformio_manager import get_pio_command
from .state import FrameRecord


def format_bitmap_array(name: str, bitmap: List[int]) -> List[str]:
    lines = [f"const uint8_t {name}[] PROGMEM = {{"]
    for offset in range(0, len(bitmap), 16):
        chunk = bitmap[offset : offset + 16]
        line = ", ".join(f"0x{value:02X}" for value in chunk)
        lines.append(f"    {line},")
    lines.append("};")
    return lines


def render_header(frames: Iterable[FrameRecord]) -> str:
    frames = list(frames)
    lines: List[str] = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "// Auto-generated by webtool/builder.py",
        f"constexpr uint8_t WEBTOOL_BITMAP_WIDTH = {OLED_WIDTH};",
        f"constexpr uint8_t WEBTOOL_BITMAP_HEIGHT = {OLED_HEIGHT};",
        "",
        "struct FrameDescriptor {",
        "    const uint8_t* bitmap;",
        "    const char* name;",
        "    uint32_t delay_ms;",
        "};",
        "",
        "namespace WebtoolFrames {",
        "",
    ]

    array_names: List[str] = []
    for idx, frame in enumerate(frames):
        array_name = f"frame_{idx}"
        array_names.append(array_name)
        lines.extend(format_bitmap_array(array_name, frame.bitmap))
        lines.append(f"// Source: {Path(frame.source_path).name}, delay: {frame.delay_ms} ms")
        lines.append("")

    lines.append("constexpr FrameDescriptor FRAMES[] = {")
    for name, frame in zip(array_names, frames):
        safe_name = frame.name.replace('"', "")
        lines.append(
            f'    {{{name}, "{safe_name}", {frame.delay_ms}}},'
        )
    lines.append("};")
    lines.append("")
    lines.append("constexpr size_t FRAME_COUNT = sizeof(FRAMES) / sizeof(FRAMES[0]);")
    lines.append("")
    lines.append("}  // namespace WebtoolFrames")
    lines.append("")
    return "\n".join(lines)


def write_header(frames: Iterable[FrameRecord], destination: Path = GENERATED_HEADER) -> Path:
    header_text = render_header(frames)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(header_text, encoding="utf-8")
    return destination


def run_platformio() -> subprocess.CompletedProcess[str]:
    """Run PlatformIO build and upload command."""
    pio_cmd = get_pio_command()
    return subprocess.run(
        pio_cmd,
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def build_and_upload(frames: Iterable[FrameRecord]) -> dict:
    frames = list(frames)
    if not frames:
        raise ValueError("No frames available for build.")

    header_path = write_header(frames)
    result = run_platformio()
    return {
        "header": str(header_path),
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
    }
